### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by ionutvmi** [anishathalye/git-remote-dropbox#13]
I tried to get this one working on windows 7
I have managed to install the Python library for Dropbox API v2 and get the dropbox OAuth2 token.

But when I try to push it just gets stuck...
As far as I can tell it gets stuck in inside the readline() function line: ~333

```
        while True:
            line = readline()
```

**Comment by anishathalye** [comment]
Hmm... so I don't own a Windows machine, so I haven't tested on Windows yet.

I'll get a VM installed and debug this as soon as I can.

Btw, if you're trying to debug on your own, you might find it helpful to set the environment variable `GIT_TRANSPORT_HELPER_DEBUG=1`.

**Comment by anishathalye** [comment]
Okay, I started to debug this. Git talks to the remote helper by communicating to the helper's stdin and expecting answers on the helper's stdout. One of the first things it does is have the helper list its capabilities.

According to the [remote helper protocol](https://www.kernel.org/pub/software/scm/git/docs/gitremote-helpers.html), git will write `capabilities`, and then it'll keep reading lines until it sees a blank line. The issue on Windows seems to be that git doesn't recognize the empty line as the terminator.

Setting `GIT_TRANSPORT_HELPER_DEBUG=1`, we see:

```
Debug: Remote helper: -> capabilities
Debug: Remote helper: Waiting...
Debug: Remote helper: <- option
Debug: Got cap option
Debug: Remote helper: Waiting...
Debug: Remote helper: <- push
Debug: Got cap push
Debug: Remote helper: Waiting...
Debug: Remote helper: <- fetch
Debug: Got cap fetch
Debug: Remote helper: Waiting...
Debug: Remote helper: <-
Debug: Got cap
Debug: Remote helper: Waiting...
```

That last `Debug: Got cap` shouldn't be there. Instead, it should look like this (as it does on Mac OS / Linux):

```
Debug: Remote helper: -> capabilities
Debug: Remote helper: Waiting...
Debug: Remote helper: <- fetch
Debug: Got cap fetch
Debug: Remote helper: Waiting...
Debug: Remote helper: <- option
Debug: Got cap option
Debug: Remote helper: Waiting...
Debug: Remote helper: <- push
Debug: Got cap push
Debug: Remote helper: Waiting...
Debug: Remote helper: <- check-connectivity
Debug: Got cap check-connectivity
Debug: Remote helper: Waiting...
Debug: Remote helper: <-
Debug: Capabilities complete.
```

(and then it keeps going on from there, doing what it's supposed to)

At first, I thought the issue might be with LF vs CRLF line endings, but that doesn't seem to be the cause. I am not sure what is causing this - perhaps it is a bug with Git on Windows?

---

Also, there may be other minor issues with Windows compatibility, like using `os.path.join` where we might actually want `posixpath.join` when constructing paths to pass to the Dropbox API. Those things (if they're an issue) should be pretty easy to fix. Can't really work on those until this issue is fixed, though.

**Comment by anishathalye** [comment]
I've sent an email to the Git [mailing list](https://git.wiki.kernel.org/index.php/GitCommunity) to see if anyone there has any suggestions.

**Comment by anishathalye** [comment]
This has been fixed in d67d2fb6863e03deaf99c0418387feaffd8367da (currently in the develop branch). See the commit message for more information.

I tested it, and it looks like it's working fine for pushing, fetching, and cloning.

Thanks again for reporting the error, and please let me know if you see anything else weird going on.

**Comment by titonobre** [comment]
Hello,
I'm really new to Python (like 5 hours) but I think this is not fixed yet.

Environment:
* Windows 10
* git version 1.9.5.msysgit.0
* dropbox/dropbox-sdk-python@3c0131946f4c352cce614259e26401722bbfa96f

With Python 3.5.0:

```
λ git fetch
Debug: Remote helper: -> capabilities
Debug: Remote helper: Waiting...
Debug: Remote helper: <- option
Debug: Got cap option
Debug: Remote helper: Waiting...
Debug: Remote helper: <- push
Debug: Got cap push
Debug: Remote helper: Waiting...
Debug: Remote helper: <- fetch
Debug: Got cap fetch
Debug: Remote helper: Waiting...
Debug: Remote helper: <-
Debug: Got cap
Debug: Remote helper: Waiting...
```

With Python 2.7.10

```
λ git fetch
Debug: Remote helper: -> capabilities
Debug: Remote helper: Waiting...
Debug: Remote helper: <- option
Debug: Got cap option
Debug: Remote helper: Waiting...
Debug: Remote helper: <- push
Debug: Got cap push
Debug: Remote helper: Waiting...
Debug: Remote helper: <- fetch
Debug: Got cap fetch
Debug: Remote helper: Waiting...
Debug: Remote helper: <-
Debug: Capabilities complete.
Debug: Remote helper: Waiting...
Debug: Remote helper: <- a0d59cee38a385bab9bc156e3905f860016fce68 refs/heads/master
Debug: Remote helper: Waiting...
Debug: Remote helper: <-
Debug: Read ref listing.
Debug: Remote helper: -> option followtags true
Debug: Remote helper: Waiting...
Debug: Remote helper: <- unsupported
Debug: Disconnecting.
```

**Comment by anishathalye** [comment]
Uh oh, that doesn't look good. I'll take a look as soon as I can get a Windows VM running

**Comment by candidodmv** [comment]
is it opened yet this issue or was solved?

**Comment by anishathalye** [comment]
Not sure, I haven't tried it on a Windows box, but I think it's in a working state right now.

**Comment by candidodmv** [comment]
Thanks for answer @anishathalye, but could you commit and update this repo, I'm on windows and want try this.

**Comment by anishathalye** [comment]
@candidodmv I'm not sure what you mean. The latest version is on [PyPI](https://pypi.python.org/pypi/git-remote-dropbox/0.2.2).

**Comment by candidodmv** [comment]
As said by @titonobre, I'm also really new to Python(A little worst), and I didn't found information how use this library on Windows enviroment.

**Comment by anishathalye** [comment]
I think with #50, this is resolved.
